### ISSUE TITLE
Server crash when chunk is loaded in nether

### ISSUE THREAD

**Issue by Kurotama-1** [gamerpotion/DarkRPG#16]
[crash-2022-07-02_08.58.51-server.txt](https://github.com/gamerpotion/DarkRPG/files/9033176/crash-2022-07-02_08.58.51-server.txt)

**Comment by gamerpotion** [comment]
> [crash-2022-07-02_08.58.51-server.txt](https://github.com/gamerpotion/DarkRPG/files/9033176/crash-2022-07-02_08.58.51-server.txt)

Hi, just checking, where is the server hosted on?

does it only happen on the server? if you create a singleplayer game, then choose the Blazeborn origin, does it still crash for you?

**Comment by PotatoDotJar** [comment]
@Kurotama-1 That crash is due to the built in watchdog which will stop the server if a tick takes more time than the `max-tick-time` setting is set to. Try setting your `max-tick-time` property in server.properties to -1.

See https://www.mysysadmintips.com/windows/home-and-media/556-minecraft-server-crashes-server-watchdog-fatal-a-single-server-tick for details.
