### ISSUE TITLE
Roulette issues

### ISSUE THREAD

**Issue by Evo-c** [gamerpotion/DarkRPG#25]
Hi really enjoying the pack thanks for putting it together. Just curious I've spammed hundreds of diamonds testing the roulette feature but it doesn't appear to be working.

Is it a low percentage win rate or is it currently not working? Also would it be possible to add some feedback in chat letting the player know if they lost/won as it currently says nothing.

**Comment by gamerpotion** [comment]
> Hi really enjoying the pack thanks for putting it together. Just curious I've spammed hundreds of diamonds testing the roulette feature but it doesn't appear to be working.
> 
> Is it a low percentage win rate or is it currently not working? Also would it be possible to add some feedback in chat letting the player know if they lost/won as it currently says nothing.

hi, glad you are enjoying the pack. 
the roulette feature works off rolls and item weights. You may notice you get more stone than other items and thats because its weighted more than the other rare items.  Having said that you should get the other items by using 100s of diamonds. have you tried this in creative to test out?
