### ISSUE TITLE
Spawner capacity capped at 100

### ISSUE THREAD

**Issue by Lopi12** [gamerpotion/DarkRPG#40]
Hello, i was wondering if u could remove or increment the total spawn capacity of a spawner(limited spawner mod) because it's not really ideal for an exp farm and since theres already the fixmyspawnr mod for optimisation i don't really understand the use of that mod

**Comment by gamerpotion** [comment]
> Hello, i was wondering if u could remove or increment the total spawn capacity of a spawner(limited spawner mod) because it's not really ideal for an exp farm and since theres already the fixmyspawnr mod for optimisation i don't really understand the use of that mod

hi, are you playing on the official server or local singleplayer?  if you are in singleplayer you can just go into the config folder, find limitedspawners.toml and then edit it to change 100 to whatever you want.

if on the server then unfortunately we cannot change it as one of the causes of server lag is entities, and if we have lots of people running farms at same time it will lower tps.

the fixmyspawnr is just there so that people dont join servers, create some crazy farms and then leave and never return only for the farms to keep spawning
