### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by HalfEclipseWolf** [gamerpotion/DarkRPG#7]
Dark RPG has come out with it's new release 2.7e.zip and the game has somehow deleted itself from my files/modpacks and every time I try to install it, it cancels along with a message "Object reference not set to an instant of an object." A day ago it was just fine until this new update came and basically ruined my day. Is there something I need to do or is this a bug? I would really appreciate it, take your time, I'm in no hurry. Just want to continue my world with my brother.

**Comment by HalfEclipseWolf** [comment]
Fixed it, but I can only play the 2.7a.

**Comment by gamerpotion** [comment]
> Fixed it, but I can only play the 2.7a.

Hey :) sorry about that, CurseForge was down today so most files were taken offline

you can safely update to 2.7b now which should work fine also.

I am currently working on 2.8 which will also be another stable version. I have taken 2.7e, 2.7d and 2.7c offline due to some mods not being very stable
