### ISSUE TITLE
origins not working

### ISSUE THREAD

**Issue by Cestuss** [gamerpotion/DarkRPG#8]
So basdically I created a server for me and my friends, I joined it to check it out and it was working fine, except the origins mod just didnt exist for some reason. I pressed a button (pretty sure it was o or something) and it said origins wasnt installed in the server. I went out, downloaded both origins files and added them to the server, nothing. We could still play, origins just didnt work and claimed to not be installed. Am i missing something? Im using the latest server pack from curseforge and everything else is working fine as far as i can tell. 
![3dfc71c439ccbd94a4a80f13941a1844](https://user-images.githubusercontent.com/105689709/168716930-06c4b111-c3f2-410b-8f7c-a5890cada719.png)

**Comment by gamerpotion** [comment]
Hi, that is a known issue on the Forge version of the pack. I think its because its a port of the fabric version. I will contact the person who ported it to see if they can look into this.
From my testing I think the origin works in the background so your powers etc should still work (try pressing G), it just doesnt show the information when you press O on your screen.
